### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zibri** [jeroenmeulenaar/python3-mega#2]
```
from mega import Mega
m = Mega.from_ephemeral()
m.uploadfile('test.gz')

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mega/mega.py", line 188, in uploadfile
    root_id = getattr(self, 'root_id')
AttributeError: 'Mega' object has no attribute 'root_id'

**Comment by jeroenmeulenaar** [comment]
This repository only runs on python 3.
