### ISSUE TITLE
Login from_credentials error

### ISSUE THREAD

**Issue by aoterolorenzo** [jeroenmeulenaar/python3-mega#7]
Traceback (most recent call last):
  File "boot.py", line 6, in <module>
    m = Mega.from_credentials(email, password)
  File "/VirtualEnvs/TEST/lib/python3.7/site-packages/python_mega-0.1.0-py3.7.egg/mega/mega.py", line 28, in from_credentials
  File "/VirtualEnvs/TEST/lib/python3.7/site-packages/python_mega-0.1.0-py3.7.egg/mega/mega.py", line 54, in login_user
  File "/VirtualEnvs/TEST/lib/python3.7/site-packages/python_mega-0.1.0-py3.7.egg/mega/mega.py", line 76, in _login_common
TypeError: 'int' object is not subscriptable

**Comment by hadaev8** [comment]
Same

**Comment by nicourn** [comment]
When I debug the code I can find that error in function "login_user", where res type is int.

**Comment by nicourrrn** [comment]
When I debuged the code I finded that error in function "login_user", where res type is int.

**Comment by amirmohammadian** [comment]
me too
